# Generated by Django 5.2 on 2026-01-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('coupon', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PERCENT', 'Percent'), ('DIRECT', 'Direct')], default='PERCENT', max_length=20)),
                ('unit', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(default='RAZORPAY', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
